name: Deploy to Render

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
            
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get Render services
        run: |
          curl -X GET -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          https://api.render.com/v1/services

      - name: Deploy to Render
        run: |
          IMAGE_URL=${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
          SERVICE_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          https://api.render.com/v1/services | jq -r '.[] | select(.serviceName=="intens-api-2022") | .id')
          echo "Service ID: $SERVICE_ID"
          RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X POST -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"image": "'$IMAGE_URL'"}' \
          https://api.render.com/v1/services/$SERVICE_ID/deploys)
          echo "Response Code: $RESPONSE"
          cat response.json